name: novacash
description: Une nouvelle facon de gagner de l'argent

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  ussd: ^0.0.2+1
  get_version: ^0.2.2
  intl: ^0.16.1
  expandable: ^4.1.4
  flutter_share: ^1.0.5
  flutter_simple_rating_bar: 0.0.3
  url_launcher: ^5.7.10
  flutter_countdown_timer: 1.4.0
  custom_radio_grouped_button: ^1.0.6+1
  flutter_open_whatsapp: ^0.1.2
  flutter_number_picker: ^0.0.8
  easy_permission_validator: ^2.0.1
  cube_transition: ^1.0.2
  telephony: ^0.0.7
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  platform_device_id: ^0.1.3
  carousel_pro: ^1.0.0
  month_picker_dialog: ^0.3.3
  blinking_text: ^0.0.4+1
  mobile_number: ^1.0.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets_dev/icon-splash.png"
  adaptive_icon_background: "#075c45"
  adaptive_icon_foreground: "assets_dev/icon-splash-adaptive.png"
#  >>>> flutter pub run flutter_launcher_icons:main
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Brandon
      fonts:
        - asset: assets/fonts/Brandon-grotesque-light.otf
    - family: Aduma
      fonts:
        - asset: assets/fonts/Aduma.otf
    - family: Aeonik
      fonts:
        - asset: assets/fonts/Aeonik-Regular.otf
        - asset: assets/fonts/Aeonik-Thin.otf
        - asset: assets/fonts/Aeonik-Black.otf
    - family: MarkPro
      fonts:
        - asset: assets/fonts/MarkPro.ttf
        - asset: assets/fonts/MarkPro-ExtraLight.ttf
    - family: MiniSystem
      fonts:
        - asset: assets/fonts/MiniSystemRegular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
